const fs = require('fs');
const reportJS = fs.readFileSync('public/scripts/report.js','utf8');
const nm = reportJS.match(/var CAT_NAME_MAP = \{([\s\S]*?)\n  \};/);
const nameMap = {};
if (nm) {
  const pairs = nm[1].match(/'(?:[a-z0-9-]+)':\s*'(?:[^']+)'/g) || [];
  pairs.forEach(p => { const m = p.match(/'([a-z0-9-]+)':\s*'([^']+)'/); if (m) nameMap[m[1]] = m[2]; });
}

const subjs = {
  'philosophy-class': { rfs:null, rsa:[], rec:[], note:'哲学类通常不限选科。' },
  'economics-class': { rfs:null, rsa:[], rec:['思想政治'], note:'经济学类多数院校不限选科。' },
  'finance': { rfs:null, rsa:[], rec:['物理'], note:'金融学类多数不限选科，部分院校要求物理。' },
  'international-trade': { rfs:null, rsa:[], rec:[], note:'经济与贸易类通常不限选科。' },
  'public-finance': { rfs:null, rsa:[], rec:['思想政治'], note:'财政学类通常不限选科。' },
  'law-class': { rfs:null, rsa:[], rec:['思想政治'], note:'普通法学类多数不限选科。' },
  'political-science': { rfs:null, rsa:[], rec:['思想政治'], note:'政治学类通常不限选科，建议选思想政治。' },
  'sociology': { rfs:null, rsa:[], rec:[], note:'社会学类通常不限选科。' },
  'marxism': { rfs:null, rsa:[], rec:['思想政治'], note:'马克思主义理论类通常不限选科。' },
  'public-security': { rfs:null, rsa:[], rec:['思想政治'], note:'公安学类多数不限选科。' },
  'ethnology': { rfs:null, rsa:[], rec:[], note:'民族学类通常不限选科。' },
  'education': { rfs:null, rsa:[], rec:[], note:'教育学类多数不限选科。' },
  'physical-education': { rfs:null, rsa:[], rec:[], note:'体育学类通常不限选科。' },
  'chinese-literature': { rfs:null, rsa:[], rec:[], note:'中国语言文学类通常不限选科。' },
  'foreign-languages': { rfs:null, rsa:[], rec:[], note:'外国语言文学类通常不限选科。' },
  'journalism': { rfs:null, rsa:[], rec:[], note:'新闻传播学类通常不限选科。' },
  'history-class': { rfs:null, rsa:[], rec:['历史'], note:'历史学类通常不限选科，建议选历史。' },
  'mathematics': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'数学类多数要求物理和化学。' },
  'physics': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'物理学类多数要求物理和化学。' },
  'chemistry': { rfs:'物理', rsa:['物理','化学'], rec:['化学'], note:'化学类多数要求物理和化学。' },
  'biology': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'生物科学类多数要求物理和化学，部分院校对生物有额外要求。' },
  'statistics': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'统计学类多数要求物理和化学。' },
  'psychology': { rfs:null, rsa:[], rec:['物理','生物'], note:'心理学类多数不限选科，部分院校要求物理或生物。' },
  'geography': { rfs:null, rsa:[], rec:['地理'], note:'地理科学类多数不限选科，部分要求地理。' },
  'astronomy': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'天文学类要求物理和化学。' },
  'atmospheric-science': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'大气科学类多数要求物理和化学。' },
  'ocean-science': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'海洋科学类多数要求物理和化学。' },
  'geophysics': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'地球物理学类要求物理和化学。' },
  'geology': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'地质学类多数要求物理和化学。' },
  'computer-science': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'计算机类多数要求物理和化学。' },
  'electronic-information': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'电子信息类多数要求物理和化学。' },
  'energy-power': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'能源动力类多数要求物理和化学。' },
  'automation': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'自动化类多数要求物理和化学。' },
  'instrumentation': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'仪器类多数要求物理和化学。' },
  'mechanical': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'机械类多数要求物理和化学。' },
  'chemical-pharma': { rfs:'物理', rsa:['物理','化学'], rec:['化学'], note:'化工与制药类多数要求物理和化学。' },
  'transportation': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'交通运输类多数要求物理和化学。' },
  'environmental': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'环境科学与工程类多数要求物理和化学。' },
  'bioengineering': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'生物工程类多数要求物理和化学。' },
  'food-science': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'食品科学与工程类多数要求物理和化学。' },
  'electrical': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'电气类多数要求物理和化学。' },
  'water-resources': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'水利类多数要求物理和化学。' },
  'civil-engineering': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'土木类多数要求物理和化学。' },
  'materials': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'材料类多数要求物理和化学。' },
  'architecture': { rfs:null, rsa:[], rec:['物理'], note:'建筑类多数不限选科，部分院校要求物理。' },
  'aerospace': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'航空航天类多数要求物理和化学。' },
  'biomedical-eng': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'生物医学工程类多数要求物理和化学。' },
  'mechanics': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'力学类多数要求物理和化学。' },
  'surveying': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'测绘类多数要求物理和化学。' },
  'safety-eng': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'安全科学与工程类多数要求物理和化学。' },
  'geological-eng': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'地质类多数要求物理和化学。' },
  'nuclear': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'核工程类多数要求物理和化学。' },
  'ocean-engineering': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'海洋工程类多数要求物理和化学。' },
  'agricultural-eng': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'农业工程类多数要求物理和化学。' },
  'light-industry': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'轻工类多数要求物理和化学。' },
  'public-security-tech': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'公安技术类多数要求物理和化学。' },
  'mining': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'矿业类多数要求物理和化学。' },
  'textile': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'纺织类多数要求物理和化学。' },
  'ordnance': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'兵器类多数要求物理和化学。' },
  'forestry-eng': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'林业工程类多数要求物理和化学。' },
  'plant-production': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'植物生产类多数要求物理和化学。' },
  'environmental-ecology': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'自然保护与环境生态类多数要求物理和化学。' },
  'veterinary': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'动物医学类多数要求物理和化学。' },
  'animal-production': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'动物生产类多数要求物理和化学。' },
  'forestry': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'林学类多数要求物理和化学。' },
  'aquaculture': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'水产类多数要求物理和化学。' },
  'grassland-science': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'草学类多数要求物理和化学。' },
  'clinical-medicine': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'临床医学类多数要求物理和化学，部分院校建议选生物。' },
  'pharmacy': { rfs:'物理', rsa:['物理','化学'], rec:['化学'], note:'药学类多数要求物理和化学。' },
  'tcm': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'中医学类多数要求物理和化学。' },
  'nursing': { rfs:null, rsa:[], rec:['生物','化学'], note:'护理学类多数不限选科，部分院校要求化学或生物。' },
  'public-health': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'公共卫生与预防医学类多数要求物理和化学。' },
  'stomatology': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'口腔医学类多数要求物理和化学。' },
  'integrated-medicine': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'中西医结合类多数要求物理和化学。' },
  'chinese-pharmacy': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'中药学类多数要求物理和化学。' },
  'medical-technology': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'医学技术类多数要求物理和化学。' },
  'basic-medicine': { rfs:'物理', rsa:['物理','化学'], rec:['生物'], note:'基础医学类多数要求物理和化学。' },
  'forensic-medicine': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'法医学类多数要求物理和化学。' },
  'business-administration': { rfs:null, rsa:[], rec:[], note:'工商管理类通常不限选科。' },
  'public-administration': { rfs:null, rsa:[], rec:[], note:'公共管理类通常不限选科。' },
  'management-science': { rfs:null, rsa:[], rec:['物理'], note:'管理科学与工程类多数不限选科，部分要求物理。' },
  'e-commerce': { rfs:null, rsa:[], rec:[], note:'电子商务类通常不限选科。' },
  'tourism-management': { rfs:null, rsa:[], rec:[], note:'旅游管理类通常不限选科。' },
  'logistics': { rfs:null, rsa:[], rec:[], note:'物流管理与工程类通常不限选科。' },
  'industrial-engineering': { rfs:null, rsa:[], rec:['物理'], note:'工业工程类多数不限选科，部分要求物理。' },
  'library-science': { rfs:null, rsa:[], rec:[], note:'图书情报与档案管理类通常不限选科。' },
  'agri-economics': { rfs:null, rsa:[], rec:[], note:'农业经济管理类通常不限选科。' },
  'design': { rfs:null, rsa:[], rec:[], note:'设计学类通常不限选科，需艺术类专业考试。' },
  'fine-arts': { rfs:null, rsa:[], rec:[], note:'美术学类通常不限选科，需艺术类专业考试。' },
  'drama-film': { rfs:null, rsa:[], rec:[], note:'戏剧与影视学类通常不限选科，需艺术类专业考试。' },
  'music-dance': { rfs:null, rsa:[], rec:[], note:'音乐与舞蹈学类通常不限选科，需艺术类专业考试。' },
  'art-theory': { rfs:null, rsa:[], rec:[], note:'艺术学理论类通常不限选科。' },
  'interdisciplinary-class': { rfs:'物理', rsa:['物理','化学'], rec:[], note:'交叉学科类多数偏理工方向，要求物理和化学。' },
};

let out = 'var SUBJECT_REQUIREMENTS = {\n';
Object.entries(subjs).forEach(([slug, s]) => {
  out += `  '${slug}': { rfs:${s.rfs?`'${s.rfs}'`:'null'}, rsa:[${s.rsa.map(x=>`'${x}'`).join(',')}], rec:[${(s.rec||[]).map(x=>`'${x}'`).join(',')}], note:'${s.note}' },\n`;
});
out += '};\n';
fs.writeFileSync('/tmp/subject_requirements.js', out);
console.log('Generated', Object.keys(subjs).length, 'categories');
console.log('Hard block (rsa non-empty):', Object.values(subjs).filter(s=>s.rsa.length>0).length);
console.log('No requirement:', Object.values(subjs).filter(s=>s.rsa.length===0&&!s.rfs).length);
